apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "reviews"
  description: "reviews service"
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/backstage-admins"
  system: system:default/bookinfo
  providesApis: 
    - reviews